<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'e6c9d0d444a8026cac0b2ac0b4ae0b71',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'mysql://e2052824_keyShopBoard:LwkQ6637b@127.0.0.1:3306/e2052824_KeyBoardShop2',
  'STRIPE_SECRET' => 'sk_test_51MxuC6H71tQCR1NCpfpnBruCnQdLbF9hNEWtRYmmNVPHBXms7vHGpZO35nJbrYjyhDgtl8XCvAI7lhd4kelUF02500uEsDPMTV',
);
